// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_utils_upload_file = {
  file: Blob | File
}

export type GenerateContentRequest = {
  prompt: string
  provider?: string
  model?: string
  max_tokens?: number
}

export type GenerateHashtagsRequest = {
  content: string
  platform?: string
  count?: number
  max_tokens?: number
}

export type GeneratePostContentRequest = {
  post_idea: string
  business_description: string
  client_avatars?: string | null
  platform?: string
  tone?: string
  provider?: string
  model?: string
}

export type GeneratePostIdeasRequest = {
  business_description: string
  client_avatars?: string | null
  additional_instructions?: string | null
  provider?: string
  model?: string
  count?: number
}

export type GeneratePostRequest = {
  business_description: string
  client_avatars?: string | null
  platform?: string
  tone?: string
  max_tokens?: number
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpcomingPostCreate = {
  media_url: string
  text: string
  hashtags?: string
  scheduled_time: string
  to_facebook?: boolean
  to_instagram?: boolean
  to_tiktok?: boolean
}

export type UpcomingPostPublic = {
  media_url: string
  text: string
  hashtags?: string
  scheduled_time: string
  to_facebook?: boolean
  to_instagram?: boolean
  to_tiktok?: boolean
  id: string
  owner_id: string
  created_at: string
  updated_at: string
}

export type UpcomingPostsPublic = {
  data: Array<UpcomingPostPublic>
  count: number
}

export type UpcomingPostUpdate = {
  media_url?: string | null
  text?: string | null
  hashtags?: string | null
  scheduled_time?: string | null
  to_facebook?: boolean | null
  to_instagram?: boolean | null
  to_tiktok?: boolean | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  quota?: number
  usage_count?: number
  business_description?: string | null
  client_avatars?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  quota?: number
  usage_count?: number
  business_description?: string | null
  client_avatars?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  quota?: number | null
  usage_count?: number | null
  business_description?: string | null
  client_avatars?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AuthFacebookLoginResponse = unknown

export type AuthFacebookCallbackData = {
  code: string
}

export type AuthFacebookCallbackResponse = unknown

export type AuthTiktokLoginResponse = unknown

export type AuthTiktokCallbackResponse = unknown

export type PostToFacebookZ95BfvData = {
  message: string
}

export type PostToFacebookZ95BfvResponse = unknown

export type PostToTiktokI7EmjsData = {
  description: string
  videoUrl: string
}

export type PostToTiktokI7EmjsResponse = unknown

export type PostToInstagramL1Yt7MData = {
  caption: string
  imageUrl: string
}

export type PostToInstagramL1Yt7MResponse = unknown

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LlmGenerateContentData = {
  requestBody: GenerateContentRequest
}

export type LlmGenerateContentResponse = unknown

export type LlmGeneratePostIdeasData = {
  requestBody: GeneratePostIdeasRequest
}

export type LlmGeneratePostIdeasResponse = unknown

export type LlmGeneratePostContentData = {
  requestBody: GeneratePostContentRequest
}

export type LlmGeneratePostContentResponse = unknown

export type LlmGenerateSocialMediaPostData = {
  requestBody: GeneratePostRequest
}

export type LlmGenerateSocialMediaPostResponse = unknown

export type LlmGenerateHashtagsData = {
  requestBody: GenerateHashtagsRequest
}

export type LlmGenerateHashtagsResponse = unknown

export type LlmGetAvailableProvidersResponse = unknown

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UsersGetMyQuotaInfoResponse = unknown

export type UsersGetUserQuotaInfoData = {
  userId: string
}

export type UsersGetUserQuotaInfoResponse = unknown

export type UsersUpdateUserClientSpecificsData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserClientSpecificsResponse = unknown

export type UsersIncrementMyUsageResponse = unknown

export type UsersIncrementUserUsageData = {
  userId: string
}

export type UsersIncrementUserUsageResponse = unknown

export type UsersGetMyLlmUsageSummaryResponse = unknown

export type UsersGetUserLlmUsageSummaryData = {
  userId: string
}

export type UsersGetUserLlmUsageSummaryResponse = unknown

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type UtilsListUpcomingPostsData = {
  limit?: number
  skip?: number
}

export type UtilsListUpcomingPostsResponse = UpcomingPostsPublic

export type UtilsCreatePostingData = {
  requestBody: UpcomingPostCreate
}

export type UtilsCreatePostingResponse = UpcomingPostPublic

export type UtilsUpdatePostingData = {
  postId: string
  requestBody: UpcomingPostUpdate
}

export type UtilsUpdatePostingResponse = UpcomingPostPublic

export type UtilsDeletePostingData = {
  postId: string
}

export type UtilsDeletePostingResponse = {
  [key: string]: unknown
}

export type UtilsUploadFileData = {
  formData: Body_utils_upload_file
}

export type UtilsUploadFileResponse = unknown
