"""rename_upcomingpost_to_posts_add_performance_fields

Revision ID: 1f54299e916b
Revises: 400d59cddd61
Create Date: 2025-10-27 15:46:15.437540

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f54299e916b'
down_revision = '400d59cddd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, rename the table to preserve data
    op.rename_table('upcomingpost', 'posts')
    
    # Create the ENUM type first
    poststatus_enum = sa.Enum('SCHEDULED', 'POSTING', 'POSTED', 'FAILED', name='poststatus')
    poststatus_enum.create(op.get_bind())
    
    # Add new columns for status and performance tracking
    op.add_column('posts', sa.Column('status', poststatus_enum, nullable=False, server_default='SCHEDULED'))
    op.add_column('posts', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('facebook_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('instagram_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('tiktok_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('comments', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('shares', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('engagement_rate', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('posts', sa.Column('last_updated', sa.DateTime(), nullable=True))
    
    # Add indexes for better performance
    op.create_index('ix_posts_status', 'posts', ['status'])
    op.create_index('ix_posts_scheduled_time', 'posts', ['scheduled_time'])
    op.create_index('ix_posts_owner_id_status', 'posts', ['owner_id', 'status'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_posts_owner_id_status', table_name='posts')
    op.drop_index('ix_posts_scheduled_time', table_name='posts')
    op.drop_index('ix_posts_status', table_name='posts')
    
    # Drop new columns
    op.drop_column('posts', 'last_updated')
    op.drop_column('posts', 'engagement_rate')
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'shares')
    op.drop_column('posts', 'comments')
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'tiktok_post_id')
    op.drop_column('posts', 'instagram_post_id')
    op.drop_column('posts', 'facebook_post_id')
    op.drop_column('posts', 'posted_at')
    op.drop_column('posts', 'status')
    
    # Rename table back
    op.rename_table('posts', 'upcomingpost')
    
    # Drop the ENUM type
    poststatus_enum = sa.Enum('SCHEDULED', 'POSTING', 'POSTED', 'FAILED', name='poststatus')
    poststatus_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###
