"""add_quota_fields_to_user

Revision ID: 2116a5a0f56e
Revises: f6d97a0becfd
Create Date: 2025-06-27 01:57:30.561866

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2116a5a0f56e'
down_revision = 'f6d97a0becfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('user', sa.Column('quota', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('business_description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('user', sa.Column('client_avatars', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE \"user\" SET quota = 1000, usage_count = 0 WHERE quota IS NULL")
    
    # Make columns non-nullable
    op.alter_column('user', 'quota', nullable=False)
    op.alter_column('user', 'usage_count', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'client_avatars')
    op.drop_column('user', 'business_description')
    op.drop_column('user', 'usage_count')
    op.drop_column('user', 'quota')
    # ### end Alembic commands ###
