"""rename_user_table_to_toc_users

Revision ID: 400d59cddd61
Revises: 88a90a9a2867
Create Date: 2025-10-23 12:12:38.739952

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '400d59cddd61'
down_revision = '88a90a9a2867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the table from 'user' to 'toc_users'
    op.rename_table('user', 'toc_users')
    
    # Rename the index
    op.execute('ALTER INDEX ix_user_email RENAME TO ix_toc_users_email')
    
    # Update foreign key constraints to reference the new table name
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'toc_users', ['owner_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('llmusage_user_id_fkey', 'llmusage', type_='foreignkey')
    op.create_foreign_key('llmusage_user_id_fkey', 'llmusage', 'toc_users', ['user_id'], ['id'])
    
    op.drop_constraint('socialaccount_user_id_fkey', 'socialaccount', type_='foreignkey')
    op.create_foreign_key('socialaccount_user_id_fkey', 'socialaccount', 'toc_users', ['user_id'], ['id'])
    
    op.drop_constraint('upcomingpost_owner_id_fkey', 'upcomingpost', type_='foreignkey')
    op.create_foreign_key('upcomingpost_owner_id_fkey', 'upcomingpost', 'toc_users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert foreign key constraints to reference the old table name
    op.drop_constraint('upcomingpost_owner_id_fkey', 'upcomingpost', type_='foreignkey')
    op.create_foreign_key('upcomingpost_owner_id_fkey', 'upcomingpost', 'user', ['owner_id'], ['id'])
    
    op.drop_constraint('socialaccount_user_id_fkey', 'socialaccount', type_='foreignkey')
    op.create_foreign_key('socialaccount_user_id_fkey', 'socialaccount', 'user', ['user_id'], ['id'])
    
    op.drop_constraint('llmusage_user_id_fkey', 'llmusage', type_='foreignkey')
    op.create_foreign_key('llmusage_user_id_fkey', 'llmusage', 'user', ['user_id'], ['id'])
    
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    
    # Rename the index back
    op.execute('ALTER INDEX ix_toc_users_email RENAME TO ix_user_email')
    
    # Rename the table back from 'toc_users' to 'user'
    op.rename_table('toc_users', 'user')
    # ### end Alembic commands ###
