"""Add upcoming_post table for scheduled posts

Revision ID: 80e817611cb4
Revises: 1a31ce608336
Create Date: 2025-06-24 15:50:08.033879

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '80e817611cb4'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcomingpost',
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('hashtags', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('to_facebook', sa.Boolean(), nullable=False),
    sa.Column('to_instagram', sa.Boolean(), nullable=False),
    sa.Column('to_tiktok', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcomingpost')
    # ### end Alembic commands ###
