"""Add SocialAccount table for social media connections

Revision ID: f6d97a0becfd
Revises: 80e817611cb4
Create Date: 2025-06-26 23:36:53.672587

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6d97a0becfd'
down_revision = '80e817611cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialaccount',
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socialaccount')
    # ### end Alembic commands ###
